version: '3.9'

services:
    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql/

    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: php-app
        volumes:
            - ./php:/var/www/html
        environment:
            - DB_HOSTNAME=db  # Ensure this is 'db'
            - DB_DATABASE=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db

    web:
        depends_on:
            - db
            - php
        links:
            - db
            - php
        image: nginx:latest
        container_name: nginx
        restart: always
        volumes:
            - ./php:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9090:80"

volumes:
  db_data: {}