# Use the PHP image with FPM
FROM php:8.1-fpm

LABEL maintainer="iftikhar Hossain"

# Install the required PDO MySQL extension
RUN docker-php-ext-install pdo pdo_mysql

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Copy the application files
COPY index.php /var/www/html/

# Set working directory
WORKDIR /var/www/html