version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
    # environment:
    #   - JENKINS_ADMIN_ID=admin           # Set the admin username
    #   - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD} 
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins_network

volumes:
  jenkins_data:

networks:
  jenkins_network:

